"""
Tool: tools/analyze_scripts.py
Purpose: Analyse Python source files and emit a Markdown metrics table.

Metrics per file:
  - File name (relative to project root)
  - Total lines (all lines in file)
  - Code lines (non-empty, non-comment lines)
  - Average code-line length (characters)
  - File size in KB

Output: docs/CODE_METRICS.md (Obsidian-compatible Markdown table)

Usage:
    python tools/analyze_scripts.py                  # scan src/ and tests/
    python tools/analyze_scripts.py src/mymodule     # scan specific folder
    python tools/analyze_scripts.py --help

The script exits with code 1 if any file has code lines > CODE_LINE_LIMIT
(configurable below) so it can act as a CI gate.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────

# Warn / fail if a single file exceeds this many code lines.
CODE_LINE_LIMIT: int = 300

# Default scan roots (relative to project root).
DEFAULT_SCAN_ROOTS: list[str] = ["."]

# Output file (relative to project root).
OUTPUT_FILE: str = "docs/CODE_METRICS.md"

# Project root: two levels up from this file (tools/analyze_scripts.py).
_PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent


# ── Analysis ───────────────────────────────────────────────────────────────


def _is_code_line(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped) and not stripped.startswith("#")


def analyse_file(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    total_lines = len(lines)
    code_only = [ln for ln in lines if _is_code_line(ln)]
    code_lines = len(code_only)
    avg_len = round(sum(len(ln.rstrip()) for ln in code_only) / code_lines, 1) if code_lines else 0.0
    size_kb = round(path.stat().st_size / 1024, 2)

    try:
        rel_path = path.relative_to(_PROJECT_ROOT).as_posix()
    except ValueError:
        rel_path = path.as_posix()

    return {
        "path": path,
        "rel_path": rel_path,
        "total_lines": total_lines,
        "code_lines": code_lines,
        "avg_len": avg_len,
        "size_kb": size_kb,
        "over_limit": code_lines > CODE_LINE_LIMIT,
    }


def collect_files(roots: list[Path]) -> list[Path]:
    _EXCLUDED = {".venv", "__pycache__", ".git", "build", "dist", "node_modules"}
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        files.extend(
            p for p in root.rglob("*")
            if p.suffix in {".py", ".ts", ".tsx"} and not _EXCLUDED.intersection(p.parts)
        )
    return sorted(files)


# ── Markdown rendering ─────────────────────────────────────────────────────


def _flag(over: bool) -> str:
    return "⚠️ OVER" if over else "✅"


def render_markdown(metrics: list[dict], limit: int) -> str:
    from datetime import datetime

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    total_files = len(metrics)
    total_code = sum(m["code_lines"] for m in metrics)
    total_size = round(sum(m["size_kb"] for m in metrics), 2)
    over_count = sum(1 for m in metrics if m["over_limit"])

    lines: list[str] = [
        "# Code Metrics",
        "",
        f"> **Generated:** {now}  ",
        f"> **Files scanned:** {total_files}  ",
        f"> **Total code lines:** {total_code:,}  ",
        f"> **Total size:** {total_size} KB  ",
        f"> **Code line limit per file:** {limit}  ",
        f"> **Files over limit:** {over_count}",
        "",
        "---",
        "",
        "## Per-File Metrics",
        "",
        "| File | Total Lines | Code Lines | Avg Line Len | Size (KB) | Status |",
        "|------|-------------|------------|--------------|-----------|--------|",
    ]

    for m in metrics:
        lines.append(
            f"| `{m['rel_path']}` "
            f"| {m['total_lines']:,} "
            f"| {m['code_lines']:,} "
            f"| {m['avg_len']} "
            f"| {m['size_kb']} "
            f"| {_flag(m['over_limit'])} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Files Over Limit",
        "",
    ]

    over = [m for m in metrics if m["over_limit"]]
    if over:
        lines.append(f"> ⚠️ {len(over)} file(s) exceed the {limit}-line code limit.")
        lines.append("")
        for m in over:
            lines.append(f"- `{m['rel_path']}` — **{m['code_lines']} code lines**")
    else:
        lines.append(f"> ✅ All files are within the {limit}-line code limit.")

    lines += [
        "",
        "---",
        "",
        "_Generated by `tools/analyze_scripts.py`_",
    ]

    return "\n".join(lines) + "\n"


# ── CLI ────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Analyse Python source files and write docs/CODE_METRICS.md.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python tools/analyze_scripts.py
  python tools/analyze_scripts.py src/mymodule
  python tools/analyze_scripts.py --limit 200 --no-write
""",
    )
    parser.add_argument(
        "roots",
        nargs="*",
        metavar="DIR",
        help=(
            "Directories to scan (relative to project root). "
            f"Default: {DEFAULT_SCAN_ROOTS}"
        ),
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=CODE_LINE_LIMIT,
        metavar="N",
        help=f"Code-line limit per file before flagging as OVER (default: {CODE_LINE_LIMIT}).",
    )
    parser.add_argument(
        "--output",
        default=OUTPUT_FILE,
        metavar="PATH",
        help=f"Output Markdown file, relative to project root (default: {OUTPUT_FILE}).",
    )
    parser.add_argument(
        "--no-write",
        action="store_true",
        help="Print the report to stdout instead of writing to a file.",
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Exit with code 1 if any file exceeds --limit (useful in CI).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.roots:
        scan_roots = [_PROJECT_ROOT / r for r in args.roots]
    else:
        scan_roots = [_PROJECT_ROOT / r for r in DEFAULT_SCAN_ROOTS]

    files = collect_files(scan_roots)
    if not files:
        print("No Python files found.")
        return 0

    metrics = [analyse_file(f) for f in files]

    report = render_markdown(metrics, limit=args.limit)

    if args.no_write:
        print(report)
    else:
        output_path = _PROJECT_ROOT / args.output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Written: {output_path.relative_to(_PROJECT_ROOT).as_posix()}")
        print(f"  {len(metrics)} files analysed")
        print(f"  {sum(m['code_lines'] for m in metrics):,} total code lines")
        over = [m for m in metrics if m["over_limit"]]
        if over:
            print(f"  [OVER LIMIT] {len(over)} file(s) over the {args.limit}-line limit:")
            for m in over:
                print(f"     {m['rel_path']} ({m['code_lines']} code lines)")

    if args.ci and any(m["over_limit"] for m in metrics):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
